global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'chat_server'
    metrics_path: '/service/monitor'

    params:
      format: ['prometheus']
      
    static_configs:
      - targets:
          - 'chat-server:8081'

  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'
