worker-threads: 2
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

database: postgres
token_expiry_hours: 1

registry-shards-amount: 256
mailbox-queue-type: Vyukov
mailbox-registry-type: ShardedMap
limiter-registry-type: None

# change to URI of your postgres database
pg-connection: postgresql://testsuite@localhost:15433/chat_service