worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

database: postgresql

# change to URI of your postgres database
pg-connection: postgresql://testsuite@localhost:15433/chat_service