worker-threads: 4
worker-fs-threads: 2
worker-mon-threads: 1

logger-level: info

is-testing: false

server-port: 8080
monitoring-port: 8081

database: postgres
token_expiry_hours: 1

registry-shards-amount: 256
sessions-queue-type: Vyukov
sessions-registry-type: RcuFlatMap
mailbox-registry-type: ShardedMap
limiter-registry-type: ShardedMap

config-cache: ~/cache/
config-server-url: http://localhost:8083

pg-connection: postgresql://testsuite@localhost:15433/chat_service