worker-threads: 2
worker-fs-threads: 2
worker-mon-threads: 1

logger-level: debug

is-testing: true

server-port: 8080
monitoring-port: 8081

database: postgres
token_expiry_hours: 1

registry-shards-amount: 256
mailbox-queue-type: Vyukov
mailbox-registry-type: ShardedMap
limiter-registry-type: None # for testing switch off limiter


config-cache: ~/cache/
config-server-url: http://localhost:8083

pg-connection: postgresql://testsuite@localhost:15433/chat_service