worker-threads: 4
worker-fs-threads: 2
worker-mon-threads: 1

logger-level: info

is-testing: false

server-port: 8080
monitoring-port: 8081

database: postgres
token_expiry_hours: 1

registry-shards-amount: 256
mailbox-queue-type: Vyukov
mailbox-registry-type: ShardedMap
limiter-registry-type: ShardedMap

config-cache: ~/cache/
config-server-url: http://158.160.218.250:8083

# change to URI of your postgres database
pg-connection: postgresql://testsuite@localhost:15433/chat_service