OVERSEER_TASK_CONFIG:
    is_enabled: true,
    period_seconds: 10,
    inter_shard_pause_ms: 100

REGISTRY_CONFIG:
  max_queue_size: 1000,
  idle_timeout_sec: 60

SEND_LIMITER_CONFIG:
  is_enabled: true,
  token_refill_amount: 1,
  max_rps_per_user: 5,
  idle_timeout_sec: 5

POLLING_CONFIG:
  max_size: 100,
  polling_time_sec: 10