components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        monitor-task-processor:       # Make a separate task processor for administrative tasks.
            thread_name: mon-worker
            worker_threads: $worker-mon-threads
            worker_threads#fallback: 1

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
            listener-monitor:
                port: $monitoring-port
                task_processor: monitor-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dynamic-config:
            updates-enabled: true
            fs-cache-path: $config-cache
            fs-task-processor: fs-task-processor
        
        dynamic-config-client:
            config-url: $config-server-url
            http-retries: 5
            http-timeout: 20s
            service-name: chat

        dynamic-config-client-updater:
            config-settings: false
            first-update-fail-ok: true
            full-update-interval: 1m
            update-interval: 5s


        testsuite-support: {}

        congestion-control:

        http-client:
            load-enabled: $is_testing
            

        http-client-core:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: monitor-task-processor

        # Components
        user-repository-component:
            storage-type: $database
            postgres-component: chat-postgres-database
            ydb-component: chat-ydb-database

        user-service-component:
            load-enabled: true
            token-expiry-hours: $token_expiry_hours

        chat-repository-component:
            storage-type: $database
            postgres-component: chat-postgres-database
            ydb-component: chat-ydb-database

        chat-service-component:
            load-enabled: true
    
        messaging-service-component:
            load-enabled: true

        mailbox-registry-component:
            load-enabled: true
            shards-amount: $registry-shards-amount
            type: $mailbox-registry-type
        
        send-limiter-component:
            load-enabled: true
            shards-amount: $registry-shards-amount
            type: $limiter-registry-type

        sessions-registry-component:
            load-enabled: true
            registry-type: $sessions-registry-type
            queue-type: $sessions-queue-type

        garbage-collector-component:
            load-enabled: true

        # Handlers 

        # Users
        handler-user-register:
            path: /v1/users/register
            method: POST
            task_processor: main-task-processor

        handler-get-by-username:
            path: /v1/users/{username}                 
            method: GET            
            task_processor: main-task-processor 
            auth:
                types:
                  - bearer
                required: true

        handler-delete-by-username:
            path: /v1/users/{username}                 
            method: DELETE            
            task_processor: main-task-processor 
            auth:
                types:
                  - bearer
                required: true

        handler-update-by-username:
            path: /v1/users/{username}                 
            method: PATCH            
            task_processor: main-task-processor 
            auth:
                types:
                  - bearer
                required: true
        
        handler-user-login:
            path: /v1/users/login
            method: POST
            task_processor: main-task-processor

        # Messages
        handler-send-message:
            path: /v1/messages/send
            method: POST
            task_processor: main-task-processor
            max_request_size: 16000 #bytes
            auth:
                types:
                  - bearer
                required: true

        handler-start-session:
            path: /v1/messages/poll/start
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                required: true

        handler-poll-messages:
            path: /v1/messages/poll/{session_id}
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                required: true
        
        # Chats
        handler-private-chat:
            path: /v1/chats/private
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                required: true
                
        # PostgreSQL
        chat-postgres-database:
            dbconnection: $pg-connection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        profile-by-user-id-pg-cache:
            pgcomponent: chat-postgres-database
            chunk-size: 0 # due to libpq patch problem
            update-interval: 10s
        
        profile-by-username-pg-cache:
            pgcomponent: chat-postgres-database
            chunk-size: 0 # due to libpq patch problem
            update-interval: 10s
        