components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        monitor-task-processor:       # Make a separate task processor for administrative tasks.
            worker_threads: 2
            thread_name: mon-worker

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
            listener-monitor:
                port: $monitoring-port
                task_processor: monitor-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        congestion-control:

        http-client:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        # New version
        # Change v2.13 in dev-container, CMakeLists and Makefile
        # http-client-core:
        #     fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: monitor-task-processor

        # Components
        user-service-component:
            load-enabled: true
            token-expiry-hours: $token_expiry_hours
            storage-type: $database
            postgres-component: chat-postgres-database
            ydb-component: chat-ydb-database


        # Handlers 

        # Users

        handler-user-register:
            path: /v1/users/register
            method: POST
            task_processor: main-task-processor

        handler-get-by-username:
            path: /v1/users/{username}                 
            method: GET            
            task_processor: main-task-processor 
            auth:
                types:
                  - bearer
                required: true
        
        handler-user-login:
            path: /v1/users/login
            method: POST
            task_processor: main-task-processor

        # Messages
        handler-send-message:
            path: /v1/messages/send
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - bearer
                required: true
                
        # PostgreSQL
        chat-postgres-database:
            dbconnection: $pg-connection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        profile-pg-cache:
            pgcomponent: chat-postgres-database
            chunk-size: 0 # due to libpq patch problem
            update-interval: 10s
        